algoritmo "semnome"
// Função : solicitar ovalor da peça quantidade compradae informaro valor da peça
// Autor : Maria Rita
// Data : 26/04/2022
// Seção de Declarações
var
valor, qtde, total: real
inicio
// entrada
escreval ("digite a quantidade de peças compradas: ")
leia (qtde)
escreval ("digite o valor unitario de cada peça: ")
leia (valor)
//processamento
total<-valor*qtde
//saida
escreval ("o valor total da sua compra é: ",total)
fimalgoritmo
