algoritmo "estoqmedio"
// Função : calcular o estoqmedio de uma peça
// Autor : Maria Rita
// Data : 26/04/2022
// Seção de Declarações 
var
qtdemini, qtdemax, estoqmedio:real
inicio
// entrada
escreval("digite a quantidade minima de uma peça:")
leia (qtdemini)
escreval ("digite a quantidade maxima de uma peça:")
leia (qtdemax)

//processamento
estoqmedio <-(qtdemini+qtdemax)/2

//saida
escreval ("o estoqmediode produto é:",estoqmedio)

fimalgoritmo
